version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql