CREATE TABLE contacts
(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(25) NOT NULL,
    lastName VARCHAR(25) NOT NULL,
    email VARCHAR(25) NOT NULL,
    phone VARCHAR(25) NOT NULL
)